name = "Cherokee"
version = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Cherokee spellchecker"
chr = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Cherokee, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
chr = "TRANSLATE: A spellchecker for Cherokee, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.chr"

[windows]
system_product_code = "{AA3EAB0B-0938-444B-8393-D80E6B31B9FA}_is1"
legacy_product_codes = [
    { value = "396471B4-2871-4135-80AE-CECFD1CC145D", kind = "nsis" },
    { value = "CA1C6997-72FE-4860-A636-3FFB0548DF08", kind = "nsis" }
]
