template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "cher1273"
__REPO__ = "lang-chr"
__UND2C__ = "chr"
__UNDEFINED__ = "Cherokee"
__UND__ = "chr"
