template = "https://github.com/giellalt/template-lang-und"
rev_id = 345
template_sha = "f04ff6c72fd325cdfed0bbaee815bd2f43d847a7"

[replacements]
__GLOTTOLOG_ID__ = "cher1273"
__REPO__ = "lang-chr"
__UND2C__ = "chr"
__UNDEFINED__ = "Cherokee"
__UND__ = "chr"
