template = "https://github.com/giellalt/template-lang-und"
rev_id = 318
template_sha = "71a1af4cb1cb80e9b86b2e9d1c090f473b0d8270"

[replacements]
__GLOTTOLOG_ID__ = "cher1273"
__REPO__ = "lang-chr"
__UND2C__ = "chr"
__UNDEFINED__ = "Cherokee"
__UND__ = "chr"
